### ISSUE TITLE
Permissions on fg.menu assets are bad in gem

### ISSUE THREAD

**Issue by davetron5000** [schacon/showoff#10]
In latest gem version:

```
public/css/fg.menu.css
public/js/fg.menu.js
```

both end up getting installed as read/write by root only, with no access at all to non-root accounts.  This causes an uncaught exception at runtime.

**Comment by schacon** [comment]
that's interesting, but I think i understand - i'll build a new gem in the next few days that should fix this.  thanks

**Comment by davetron5000** [comment]
[sorry for messaging this direct, shouldda posted here instead ]

FWIW, versions of relevant things:

```
> gem --version
1.3.5
> ruby --version
ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]
```

**Comment by schacon** [comment]
new gem (v0.0.3) should fix all of this
