### ISSUE TITLE
json requirement not listed

### ISSUE THREAD

**Issue by charliek** [schacon/showoff#12]
Before I was able get this to run I had to install the JSON gem as well as the other dependencies listed.

I have a rather old version of ruby (1.8.6) on windows, so I am not sure if the json module is included in new versions of ruby or not, but figured I would mention it in case others ran into trouble.

**Comment by titanous** [comment]
I made a commit a few days ago that should have fixed this.

http://github.com/schacon/showoff/commit/0ae0180aa829199994ee9afb8d6fd783d0d0be46

**Comment by schacon** [comment]
updated the readme to mention this, too
