### ISSUE TITLE
Could not gem install on Windows 7

### ISSUE THREAD

**Issue by antonarhipov** [schacon/showoff#122]
Tried to install the gem on Win7 machine with the following result:

C:>gem install showoff
Building native extensions.  This could take a while...
ERROR:  Error installing showoff:
        ERROR: Failed to build gem native extension.

C:/ruby187/bin/ruby.exe extconf.rb
checking for re.h... no
checking for ruby/st.h... no
creating Makefile

make
Makefile:121: **\* target pattern contains no `%'.  Stop.

Gem files will remain installed in C:/ruby187/lib/ruby/gems/1.8/gems/json-1.5.4 for inspection.
Results logged to C:/ruby187/lib/ruby/gems/1.8/gems/json-1.5.4/ext/json/ext/parser/gem_make.out

Is there any tips how to overcome this problem?

**Comment by schacon** [comment]
I haven't used windows in a hundred years, certainly never for dev, so take this with that in mind.  however, it looks like you need to install ruby-dev - it doesn't look like you have the ruby development headers and stuff.

**Comment by antonarhipov** [comment]
Indeed! installed DevKit and it solved the issue. Thx!
