### ISSUE TITLE
clicking an inner node in toc errors

### ISSUE THREAD

**Issue by xiongchiamiov** [schacon/showoff#14]
Specifically, it gives a blank page, with the footer showing NaN/16.  Debug mode shows "key: 67", which is what it shows for every other page as well.

**Comment by schacon** [comment]
yeah, only the leafs work - i would like it to show the first leaf that would be reached, but the menu system doesn't currently set the property that the js needs to find that slide.  i'll fix it soon (or would be happy to accept a patch ;)

**Comment by schacon** [comment]
i fixed this so that the subsections go to the appropriate slide
