### ISSUE TITLE
No command 'showoff' found

### ISSUE THREAD

**Issue by tonyyet** [schacon/showoff#142]
I installed showoff on my Ubuntu laptop using the "gem install showoff" command. But somehow when I navigate to the showoff directory and run "showoff serve", it just shows me this:

```
No command 'showoff' found, did you mean:
 Command 'showorf' from package 'emboss' (universe)
showoff: command not found
```

How can I get it running?

**Comment by reactormonk** [comment]
https://bugs.launchpad.net/ubuntu/+source/gems/+bug/145267

**Comment by dsengupta** [comment]
even i am getting this error ,can any1 suggest a way how to deal with it ?

**Comment by dsengupta** [comment]
its urgent

**Comment by rctay** [comment]
This is an issue with Ubuntu. As a workaround, you can try:
1. find location of the installed showoff gem
2. substitute it for `showoff <command>` eg. instead of `showoff serve`, use `/path/to/gem/bin/showoff serve`
