### ISSUE TITLE
showoff doesn't work under my Mac with chrome or safari

### ISSUE THREAD

**Issue by fujohnwang** [schacon/showoff#143]
did I miss something or showoff just work under specific environments?

as to "doesn't work" ,  I means I can't page down/page up , just the first page stand still, no matter what I do, click keys or mouses, nothing happens. :-(

**Comment by shamansir** [comment]
See Issue #144 / Pull Request #144 and merge with it, it is a bug with logger in current version

**Comment by goncalossilva** [comment]
I believe this was fixed 2 days ago. Please try it out and re-open if the issue is still there.
