### ISSUE TITLE
Sinatra(?) deprecation warning

### ISSUE THREAD

**Issue by ravinggenius** [schacon/showoff#159]
I get the following warning when starting `showoff serve`:

```
:public is no longer used to avoid overloading Module#public, use :public_folder instead
    from showoff-0.7.0/lib/showoff.rb:39:in `<class:ShowOff>'
```

**Comment by goncalossilva** [comment]
I believe this is fixed on master, so I'm closing this. Please reopen if you hit this problem again.

**Comment by travisvalentine** [comment]
I just got this error too. Running 1.9.3 and attempting to do `showoff add introduction`.

**Comment by goncalossilva** [comment]
@schacon should be releasing a new version soon. Until then, please use showoff from the master branch.

**Comment by remyleone** [comment]
@goncalossilva  I got the same problem. When is the new version coming?
