### ISSUE TITLE
bad image vertical alignment

### ISSUE THREAD

**Issue by technoweenie** [schacon/showoff#16]
I've been adding image slides with headers like this:

```
!SLIDE center

# heading #

![alt](img.jpg)
```

Sometimes when I run through the slides, the heading is in the center (vertically), and the image is underneath, getting cut off at the bottom of the slide area.  I refresh, and it's fine.  It all seems to be very intermittent. 

Is this a known bug?  Should I just leave out the headers?

**Comment by schacon** [comment]
it has nothing to do with the headers - images just do that sometimes.  i think it's because i'm setting the height dynamically and sometimes it thinks the height of the image is 0.  I haven't figured out why yet.  I'll work on it.

**Comment by technoweenie** [comment]
Ah hmm...   What if you could analyze the images and write the height/width values?  I'll poke around with that.  I kind of have a talk tonight :)  Not to put any pressure on you of course.  Thanks for the info!

**Comment by technoweenie** [comment]
Easy peasy!  http://github.com/technoweenie/showoff/commit/f1240e78eeed8c2f8f49cff48167044794bba30a

**Comment by krisb** [comment]
I've fixed this on my fork using a jquery plugin that waits for all the images to be reload before resizing the slides.

http://github.com/krisb/showoff/commit/a92cf9226335995a1103fa06bce5eaf4ab057921

**Comment by technoweenie** [comment]
That doesn't work for me.  See http://img.skitch.com/20100401-tm5xtxd1awi6ptfjtd1cjgijtg.png.  I can replicate it by doing a shift + reload in Chrome.

I've rewritten the commit adding RMagick: http://github.com/technoweenie/showoff/commit/96642d5bb852b72f435e75b948cf043b07ec6060

I realize that RMagick isn't a favorite gem, but it's on Heroku by default...

**Comment by ngauthier** [comment]
I fixed it with some simple CSS to use table-centering. Works in webkit/gecko. Doesn't work in IE. But cmon, it's presentation software for coders!

http://github.com/ngauthier/showoff

**Comment by technoweenie** [comment]
Ha, why is everyone so scared of RMagick?  No, I know the answer already :)

I can definitely appreciate a simple JS or CSS tweak that works well enough to keep one more _optional_ dependency out of ShowOff.  This doesn't even work in IE 8 though?  At any rate, this patch works for me in Chrome, Safari, and Firefox.  Image tags without size attributes bug me, but I'll deal...

**Comment by ngauthier** [comment]
I love rmagick, but it just feels silly to use javascript and pixel margins to center something. The browser can handle it. Dunno if IE8 can do it, I just wasn't willing to test it in IE8, seeing as I doubt anyone who would ever use showoff is using IE.

Also, my patch is smaller than your patch :-D

**Comment by technoweenie** [comment]
Wait, did you just turn this into a size contest?  Typical!

**Comment by davetron5000** [comment]
I have noticed that specifying an image via HTML and giving it an explicit height seems to avoid this problem:

```
!SLIDE center
(Foo)[some_image.png]
```

Renders with the image way too "low" on the page, often cut off

```
!SLIDE center
<img src="some_image.png" height="400" />
```

The image is more centered on the slide.  "height" can be the actual height of the image or not

**Comment by technoweenie** [comment]
davetron: That's actually what my patch does.  It fills in both the width and height values with RMagick.  Have you tried ngauthier's latest patch though?  That worked fine for me too.  It's a lighter weight patch that uses CSS instead.

**Comment by technoweenie** [comment]
Oh snap, it looks like Scott merged my patch in :)  davetron: if you have RMagick installed, let me know if you still see the problem.

**Comment by ngauthier** [comment]
Aw he picked the bigger patch. I guess it was a size contest :-D

**Comment by davetron5000** [comment]
This is still happening for me; it seems to go away once I specify the height (even if it's the actual height of the image).  I'm running on trunk.   Pull this:

```
git clone http://github.com/davetron5000/sneaking-scala.git
cd sneaking-scala
git checkout 5f2e21f264f3bef1323d271be35ae5acb7999e89
showoff serve
```

Go to the slide that starts "Engineering Lead" and incrementally reveal the bullets; the last one is an image that gets chopped because the entire thing is too low on the page.  Now:

```
git checkout e060c3e7e496af3754584a92e94d2b5d0143575a
showoff serve
```

go to the same slide; now it works, because I ditched markdown and explicitly set the height to the actual image height.

**Comment by ngauthier** [comment]
my patch fixes this. pull from my repository, or just add the 7 lines of CSS I wrote to your own CSS file:

http://github.com/ngauthier/showoff/commit/dc460316b24c5954084b30d7b5227d46684b1076

**Comment by jacobo** [comment]
@ngauthier any chance you could share those 7 lines of CSS here for future googlers?
