### ISSUE TITLE
Can't add images

### ISSUE THREAD

**Issue by travisvalentine** [schacon/showoff#176]
For some reason when I try to add an image with markdown it crashes the presenter and gives me a huge error. Does anyone know what might be causing this?

To run it from presenter view, go to: [ http://localhost:9090/presenter ]

---

[2012-04-05 22:34:34] INFO  WEBrick 1.3.1
[2012-04-05 22:34:34] INFO  ruby 1.9.2 (2012-02-14) [x86_64-darwin11.3.0]
== Sinatra/1.3.2 has taken the stage on 9090 for development with backup from WEBrick
[2012-04-05 22:34:34] INFO  WEBrick::HTTPServer#start: pid=81813 port=9090
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
localhost - - [05/Apr/2012:22:34:36 EDT] "GET / HTTP/1.1" 200 3026
- -> /
  Sinatra::Base#options is deprecated and will be removed, use #settings instead.
  localhost - - [05/Apr/2012:22:34:36 EDT] "GET /file/test.css HTTP/1.1" 304 0
  http://localhost:9090/ -> /file/test.css
  Sinatra::Base#options is deprecated and will be removed, use #settings instead.
  Sinatra::Base#options is deprecated and will be removed, use #settings instead.
  Sinatra::Base#options is deprecated and will be removed, use #settings instead.
  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:206: [BUG] Segmentation fault
  ruby 1.9.2p318 (2012-02-14 revision 34678) [x86_64-darwin11.3.0]

-- control frame ----------
c:0061 p:---- s:0290 b:0290 l:000289 d:000289 CFUNC  :ping
c:0060 p:0042 s:0286 b:0286 l:000285 d:000285 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:206
c:0059 p:0036 s:0281 b:0281 l:000267 d:000280 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:194
c:0058 p:---- s:0274 b:0274 l:000273 d:000273 FINISH
c:0057 p:---- s:0272 b:0272 l:000271 d:000271 CFUNC  :gsub
c:0056 p:0116 s:0268 b:0268 l:000267 d:000267 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:192
c:0055 p:0341 s:0259 b:0259 l:000244 d:000258 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:170
c:0054 p:---- s:0250 b:0250 l:000249 d:000249 FINISH
c:0053 p:---- s:0248 b:0248 l:000247 d:000247 CFUNC  :each
c:0052 p:0231 s:0245 b:0245 l:000244 d:000244 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:146
c:0051 p:0080 s:0232 b:0231 l:000212 d:000230 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:283
c:0050 p:---- s:0227 b:0227 l:000226 d:000226 FINISH
c:0049 p:---- s:0225 b:0225 l:000224 d:000224 CFUNC  :each
c:0048 p:0142 s:0222 b:0222 l:000212 d:000221 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:281
c:0047 p:---- s:0218 b:0218 l:000217 d:000217 FINISH
c:0046 p:---- s:0216 b:0216 l:000215 d:000215 CFUNC  :each
c:0045 p:0071 s:0213 b:0213 l:000212 d:000212 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:272
c:0044 p:0017 s:0205 b:0205 l:000204 d:000204 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:374
c:0043 p:0082 s:0201 b:0201 l:001e08 d:000200 LAMBDA /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:487
c:0042 p:---- s:0197 b:0197 l:000196 d:000196 FINISH
c:0041 p:---- s:0195 b:0195 l:000194 d:000194 CFUNC  :call
c:0040 p:0020 s:0192 b:0192 l:001680 d:000191 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212
c:0039 p:---- s:0188 b:0188 l:000187 d:000187 FINISH
c:0038 p:---- s:0186 b:0186 l:000185 d:000185 CFUNC  :[]
c:0037 p:0014 s:0181 b:0181 l:000140 d:000180 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:785
c:0036 p:0010 s:0179 b:0177 l:000176 d:000176 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:801
c:0035 p:0009 s:0174 b:0174 l:000140 d:000173 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:785
c:0034 p:0041 s:0171 b:0171 l:000162 d:000170 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:822
c:0033 p:---- s:0169 b:0169 l:000168 d:000168 FINISH
c:0032 p:---- s:0167 b:0167 l:000166 d:000166 CFUNC  :catch
c:0031 p:0190 s:0163 b:0163 l:000162 d:000162 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:820
c:0030 p:0018 s:0152 b:0152 l:000140 d:000151 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:784
c:0029 p:---- s:0146 b:0146 l:000145 d:000145 FINISH
c:0028 p:---- s:0144 b:0144 l:000143 d:000143 CFUNC  :each
c:0027 p:0050 s:0141 b:0141 l:000140 d:000140 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:783
c:0026 p:0078 s:0135 b:0135 l:000134 d:000134 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:886
c:0025 p:0009 s:0131 b:0131 l:000116 d:000130 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:719
c:0024 p:0005 s:0129 b:0129 l:000120 d:000128 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:871
c:0023 p:---- s:0127 b:0127 l:000126 d:000126 FINISH
c:0022 p:---- s:0125 b:0125 l:000124 d:000124 CFUNC  :catch
c:0021 p:0013 s:0121 b:0121 l:000120 d:000120 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:871
c:0020 p:0136 s:0117 b:0117 l:000116 d:000116 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:719
c:0019 p:0019 s:0113 b:0113 l:000112 d:000112 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:705
c:0018 p:0015 s:0109 b:0109 l:000108 d:000108 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22
c:0017 p:0055 s:0102 b:0102 l:000101 d:000101 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16
c:0016 p:0019 s:0097 b:0097 l:000096 d:000096 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17
c:0015 p:0075 s:0089 b:0089 l:000088 d:000088 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47
c:0014 p:0015 s:0084 b:0084 l:000083 d:000083 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22
c:0013 p:0070 s:0077 b:0077 l:000076 d:000076 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/logger.rb:15
c:0012 p:0015 s:0072 b:0072 l:000071 d:000071 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/head.rb:9
c:0011 p:0095 s:0065 b:0065 l:000064 d:000064 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/methodoverride.rb:21
c:0010 p:0015 s:0060 b:0060 l:000059 d:000059 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/showexceptions.rb:21
c:0009 p:0018 s:0052 b:0052 l:001a00 d:000051 BLOCK  /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334
c:0008 p:0032 s:0050 b:0050 l:000049 d:000049 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416
c:0007 p:0011 s:0046 b:0046 l:001a00 d:001a00 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334
c:0006 p:0356 s:0042 b:0042 l:000041 d:000041 METHOD /Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59
c:0005 p:0257 s:0030 b:0030 l:000029 d:000029 METHOD /Users/travisvalentine/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/httpserver.rb:111
c:0004 p:0393 s:0020 b:0020 l:000019 d:000019 METHOD /Users/travisvalentine/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/httpserver.rb:70
c:0003 p:0126 s:0009 b:0009 l:001088 d:000008 BLOCK  /Users/travisvalentine/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/server.rb:183
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
## c:0001 p:---- s:0002 b:0002 l:000001 d:000001 TOP   

-- Ruby level backtrace information ----------------------------------------
/Users/travisvalentine/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
/Users/travisvalentine/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/httpserver.rb:70:in`run'
/Users/travisvalentine/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in`service'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in`synchronize'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/showexceptions.rb:21:in`call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/head.rb:9:in`call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in`call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in`call!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in`catch'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in`block in call!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:886:in `dispatch!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in`route!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `each'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:784:in`block in route!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `process_route'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in`catch'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `block in process_route'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in`block (2 levels) in route!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:801:in `route_eval'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in`block (3 levels) in route!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `[]'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in`block in compile!'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:487:in`block in class:ShowOff'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:374:in `slides'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:272:in`get_slides_html'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:272:in `each'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:281:in`block in get_slides_html'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:281:in `each'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:283:in`block (2 levels) in get_slides_html'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:146:in `process_markdown'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:146:in`each'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:170:in `block in process_markdown'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:192:in`update_image_paths'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:192:in `gsub'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:194:in`block in update_image_paths'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:206:in `get_image_size'
/Users/travisvalentine/.rvm/gems/ruby-1.9.2-p318/gems/showoff-0.7.0/lib/showoff.rb:206:in`ping'

-- C level backtrace information -------------------------------------------

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

**Comment by alexch** [comment]
Try upgrading your Ruby. (Latest is ruby-1.9.3-p125 according to RVM.)
That tends to fix most seg faults in my experience. Ruby 1.9.3 is
basically the same as 1.9.2 and adds some bug fixes and API calls, so
it shouldn't be a big deal. YMMV :-)

**Comment by travisvalentine** [comment]
Yeah I've tried both 1.9.2 and 1.9.3. Here's the markdown syntax I'm using for a picture that's in the same folder as my markdown file:

!SLIDE full-page

# Testing

![test](testing.jpg)

If I use that markdown syntax on a preview editor like github's it looks right. But using it in my markdown crashes my server.

**Comment by goncalossilva** [comment]
Do you get this error on master?

**Comment by travisvalentine** [comment]
Yep, I'm on master with this.

**Comment by travisvalentine** [comment]
I figured out what was going on. It was a Ruby version issue. Running with 1.8.7 fixed everything.

**Comment by goncalossilva** [comment]
Do you get this on the latest 1.9.3?
