### ISSUE TITLE
Keyboard navigation is broken when using Pocket Chrome extension

### ISSUE THREAD

**Issue by echristopherson** [schacon/showoff#186]
I have Pocket's Chrome extension installed http://www.getpocket.com. Apparently that extension interferes with ShowOff's keyboard navigation. Disabling the extension makes navigation work. Is this something I should report to Pocket, or can you fix it?

The specific slideshow I tried is at https://github.com/rkh/presentations/tree/beyond-ruby; and I have ShowOff 0.7.0 cd36eac, installed with bundler by that presentation.

Here's a little JavaScript that Pocket inserts (under file chrome://<extensionID>/js/keyboard-shortcut.js). I'm not sure this is the ultimate culprit:

```
document.onkeydown = function(e) {
    e = e || window.event;
    var k = e.which || e.charCode || e.keyCode;

    if(((e.ctrlKey && !e.metaKey) || (!e.ctrlKey && e.metaKey)) && !e.altKey && e.shiftKey && k ==  80){
        chrome.extension.sendRequest({action: "keyboardShortcutEnabled"}, function(response){
            if(response.keyboardShortcutEnabled){
                chrome.extension.sendRequest({action: "addURL", title: document.title, url: window.location.toString()})
            }
        })
        return false;
    }

    return true;
}
```

**Comment by ashmckenzie** [comment]
+1

I was able to stay in Chrome by running within 'Incognito Mode' as a workaround if that's any consolation.

**Comment by ku1ik** [comment]
I have the same issue. But I suppose this should be reported to Pocket. Extension is installing some keyboard handlers into a page and these handlers apparently hijack too much.

**Comment by rctay** [comment]
@sickill agreed this should be reported to Pocket instead.
