### ISSUE TITLE
can't run server on mac os x mountain lion

### ISSUE THREAD

**Issue by gureckis** [schacon/showoff#192]
hi, i installed all the dependencies I think are necessary but showoff fails with

iceberg:example $ showoff serve 
You should include GLI::App instead
GLI.run no longer works for GLI-2, you must just call `run(ARGV)' instead
either fix your app, or use the latest GLI in the 1.x family

Any advice?

(I installed gem both from default repository and directly from the current github archive)

thanks

**Comment by nictrix** [comment]
I actually had to change line 8 in bin/showoff to:

include GLI::App

and at the very last line do this instead of whatever is there:

exit run(ARGV)

Then it seemed to work for me.

Thanks,
Nick

**Comment by gureckis** [comment]
Yeah that worked for me as well!

**Comment by krimple** [comment]
I tried this. I get a generic message from GLI about --help and it never delegates to showoff.

Can somebody post a working script?

**Comment by lesjames** [comment]
I ran into this problem too. I followed nictrix's suggestion and it works for me.

**Comment by AndyBean** [comment]
This bug still persists and the fix still works. Thank you @nictrix.

**Comment by durin42** [comment]
@AndyBean master works for me just fine on a couple of 10.8 machines, FWIW.

**Comment by AndyBean** [comment]
Thanks @durin42, perhaps when I cloned the repo today, March 7, 2013, I didn't get the most recent pull on master but nictrix's clever two line patch got me in working order.

-- Edit, Ah, Master is current with the fix but the gem that is available via RVM bundler was not.

**Comment by Voronchuk** [comment]
@nictrix your solution helped, thanks!
