### ISSUE TITLE
GLI.run no longer works for GLI-2, you must just call `run(ARGV' instead

### ISSUE THREAD

**Issue by robertmain** [schacon/showoff#212]
Basically what it says. When I try to run showoff serve I get this:

> $ showoff serve
> image sizing disabled - install rmagick
> :public is no longer used to avoid overloading Module#public, use :public_dir instead>
>     from /var/lib/gems/1.9.1/gems/showoff-0.7.0/lib/showoff.rb:39:in `<class:ShowOff>'
> You should include GLI::App instead
> GLI.run no longer works for GLI-2, you must just call`run(ARGV)' instead
> either fix your app, or use the latest GLI in the 1.x family

**Comment by robertmain** [comment]
_crickets_

**Comment by rctay** [comment]
Duplicate of #209

**Comment by robertmain** [comment]
Is there a fix for this? I need to do a presentation in a couple of weeks and I would like to use showoff but if this is not likely to be fixed soon it would be helpful to know so I can use something else.
