### ISSUE TITLE
Issue: Nobody Reads The Issues on This Repo

### ISSUE THREAD

**Issue by robertmain** [schacon/showoff#213]
Not sure what else to say. Was hoping to get it working, so far unable to do so on windows or linux.

...derp.

**Comment by rctay** [comment]
I guess this proves you wrong! :grin:

**Comment by alexch** [comment]
Shameless self-promotion: try [https://github.com/alexch/deck.rb](Deck) for a Markdown-to-HTML-slide Ruby app with fewer open issues than showoff. Also many fewer users :-)

**Comment by rctay** [comment]
We should have a section in the readme talking about showoff-inspired work like yours (is it one?)
