### ISSUE TITLE
Add permalinks to slides or sections

### ISSUE THREAD

**Issue by n1k0** [schacon/showoff#32]
It would be kinda great to be able to have anchors targetting a given slide or section in the presentation url, especially when working on big presentations... For the moment I just comment/uncomment sections in the json file but it's a bit boring and I'm quite lazy ;)

Anyway thousands thanks for the awesome tool.

**Comment by roidrage** [comment]
+1 on this, I thought about adding something like this. Maybe I just will, every slide already has a marker using the rel attribute.
