### ISSUE TITLE
make it ruby 1.9

### ISSUE THREAD

**Issue by badboy** [schacon/showoff#33]
please make it compatible to ruby 1.9

I will also look into it when I find some time.

**Comment by phoet** [comment]
at least mention it on the readme, that it won't work with 1.9

**Comment by nihar** [comment]
Presentation works with Ruby 1.9 if you change "require 'ftools'" to "require 'fileutils'" in showoff.rb

**Comment by nono** [comment]
You can see my pull request for this change: http://github.com/schacon/showoff/pull/41

**Comment by wingrunr21** [comment]
Please pull nono's changes.  1.9 compatibility is highly needed.

**Comment by badboy** [comment]
Fixed in e01d4ef29b204e5674bacff208c3d9ac63bae338
