### ISSUE TITLE
Static HTML should use relative links

### ISSUE THREAD

**Issue by ramereth** [schacon/showoff#34]
Generating a static HTML page currently sets all the images to point to the absolute filesystem paths of images. This makes it quite annoying if I wanted to post my static slides on a webserver for folks to look at so they don't need to setup and run showoff.

Could there be a feature added to set relative links to all the objects and also copy all the related content (images, custom css, etc) into the static folder as well?

Thanks-

**Comment by n1k0** [comment]
Agreed. Also in a static html export of a presentation of mine my custom stylesheet is referenced with `<link rel="stylesheet" href="file/styles.css" type="text/css"/>`, and there's no `file` directory within the `static` generated one.

**Comment by badboy** [comment]
static now used relative links and includes custom css and js as of 769bc24a17f179e27eb0ce454187fbe1673c6663
Only code highlighting fails to work.

This issue can be closed.

**Comment by ggilder** [comment]
I don't think the issue has been completely resolved - I built the gem from the latest head and image files on slides are still not being copied when you generate the static build. Instead you get absolute filesystem references like file:///Users/ggilder/presentation/one/rainbows.gif

**Comment by badboy** [comment]
It was changed back in 13c5821be4ed28155c0eacc45fa700b771598bd7 -_-

**Comment by ggilder** [comment]
Do you know the reason why? It seems kind of counter-intuitive... I would guess that a fairly common reason to generate the static version would be for uploading to another server, packaging up to email to someone, etc... seems like the ideal solution for those situations would be to copy in referenced images to the "file" folder. What was the rationale behind switching it back to absolute URLs?

**Comment by n1k0** [comment]
I'm not here to troll or fud, just to highlight this feature I just implemented in [landslide](http://github.com/n1k0/landslide) (just in my fork atm), so you guys might have a look at the code, it's quite easy to implement, and allow to host a standalone presentation statically just by putting it under some webserved directory (eg. this [presentation](http://akei.com/presentations/2011-Djangocong/index.html))

**Comment by badboy** [comment]
@ggilder: I think it was switched back to the file://-url style because only this way images are included in a generated pdf.
But this is definitely not what one want in a static presentation.

If no one solved this problem by next week (oh, th time, the time...), I will look into it to support both versions (`file://` for pdf and `./file/` for static)

@n1k0: Thanks, I will also look into it.

**Comment by badboy** [comment]
Filed a pull-request (#85).
Maybe it would be even better to remove the `static` boolean in place of a symbol like `:pdf` or `:static` to decide which URI-style should be used.
Let's move the discussion over there.

**Comment by bowsersenior** [comment]
Can you push a new version of the showoff gem so this fix is included? Without this fix, it's a pain to put pages on Girthub pages or other static servers.
