### ISSUE TITLE
title is alway set to 'testing'

### ISSUE THREAD

**Issue by phoet** [schacon/showoff#38]
is there no way to control the title of the slides?

i did not find anything in the docs.

have a look of your own: http://phoet-aboutme.heroku.com/

**Comment by schacon** [comment]
it's a stub for pulling the title out of the new fields in showoff.json - i'll get to it soonish.  feel free to send a patch

**Comment by phoet** [comment]
i might have a look at it tomorrow

**Comment by phoet** [comment]
i fixed this and added some spec. patch is here:

http://dl.dropbox.com/u/153067/title_from_json_with_spec.diff

**Comment by phoet** [comment]
PATCH PATCH PATCH :P

**Comment by phedders** [comment]
phoet - might get a quicker responce from a github send pull request... :O)

**Comment by schacon** [comment]
you would have, but i pulled this in already.
