### ISSUE TITLE
static not identical to serve?

### ISSUE THREAD

**Issue by icco** [schacon/showoff#49]
I'm noticing small differences between the served version of my slide show and the static version. 

The two main differences are the static version are:
- title not getting added to the static version from my json file
- the css is different
  - served version is vertically centered
  - static version is vertically aligned at the top

Noticed in this presentation: http://github.com/icco/intro-to-vim-talk

**Comment by rctay** [comment]
Take a look at my pull request:

http://github.com/schacon/showoff/issues#issue/44

Try merging it in and see if it helps with the centering part.

For the title part - not too sure.

**Comment by icco** [comment]
That pull request would be so much better if it was only the one line commit, but yes it fixes my centering problem. thanks.

**Comment by icco** [comment]
Alright, I submitted #50, so I'm closing this.
