### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by defunkt** [schacon/showoff#5]
I'm on my way out the door right now (otherwise I'd send a patch) but here's what I'd love:

If a `.css` file lives in directory, it'll be loaded for those slides. So the `something.css` file found in [the example](http://github.com/schacon/showoff/tree/master/example/one/) would be included when rendering `one/slidesA.md` and `one/slidesB.md`

**Comment by schacon** [comment]
Yeah, that's why I had that there, but I'm not sure how to dynamically load css and then turn it back off again.

**Comment by defunkt** [comment]
I've done it before, I'll take a stab at it.

**Comment by xaviershay** [comment]
good

**Comment by schacon** [comment]
merged in a fix to include extra css, but it doesn't selectively load it for just one section.  good first start, i think

**Comment by schacon** [comment]
after talking this over with defunkt, i think we agree that this functionality is fine - it loads custom css globally
