### ISSUE TITLE
ftools removed in 1.9

### ISSUE THREAD

**Issue by remarkbob** [schacon/showoff#51]
ftools is removed in 1.9.  replace with fileutils.
http://pragdave.blogs.pragprog.com/pragdave/2008/04/ruby-19-standar.html

**Comment by nono** [comment]
Scott just merged my commit (http://github.com/schacon/showoff/commit/e01d4ef29b204e5674bacff208c3d9ac63bae338), so it's fixed in master :-)

**Comment by badboy** [comment]
can be closed.

**Comment by schacon** [comment]
sweet
