### ISSUE TITLE
The only response I see is "NaN/0 - NaN%" in the status bar.

### ISSUE THREAD

**Issue by 5v3n** [schacon/showoff#55]
The only response I see is "NaN/0 - NaN%" in the status bar.

I tried 1.9.2 first, then switched to ree - see this [gist](https://gist.github.com/666052) for my Gemfile & .rvmrc.

Showoff seems to be a great concept, but this project needs a little tlc I guess ;-)... I see some quick wins (bundler, rvm, up to date gemspec) and some major work to do (tests!).

For the short run, I'd be glad if it would run in the first place ;-). 

So, what did I probably do wrong?

**Comment by roidrage** [comment]
Showoff has been working pretty well for me for months now. It does have some situations though, where the NaN can show up, and I'll be happy to fix those, since I wrote the code originally. So it'd be a lot more helpful if you could show the source of an example presentation that fails for you, or at least include a list of commands that cause a failing presentation.

**Comment by 5v3n** [comment]
Oh, I thought that would be needless to say: I'm just trying to show the example presentations I git cloned from schacon/showoff. The NaN status appears right after calling localhost:9090.

**Comment by roidrage** [comment]
It's only one presentation, just run showoff serve inside the example/ directory, and you're golden. The showoff command is looking for a showoff.json file which is only in that directory.

**Comment by 5v3n** [comment]
Thanks, that did the trick. 

Perhaps the corresponding part in the readme is not that clear about this:

> If you run ‘showoff’ in the ShowOff directory itself, it will show an example presentation from the ‘example’ subdirectory, so you can see what it’s like.

I saw a pending pull request - [issue 54](https://github.com/schacon/showoff/issues#issue/54) already addresses this issue.
