### ISSUE TITLE
Swiping advances too far on iOS devices

### ISSUE THREAD

**Issue by davetron5000** [schacon/showoff#57]
On your iPad, go to http://awesome-cli-ruby.heroku.com.  Swipe away.  Things look good.  This is on an older version of showoff, I think 0.2.5

Now, go to http://scala-boss.heroku.com.  This is running the latest version, and when you swipe, it skips too many slides at once.

**Comment by badboy** [comment]
Swiping doesn't work as expected on my Nexus One. Swiping works for 2-3 slides, then quickly counts all slides up to the end (or backwards).

I will definitely look into this tomorrow 'cause this really bugs me.
