### ISSUE TITLE
JS error: $("#navmenu").menu is not a function

### ISSUE THREAD

**Issue by corntrace** [schacon/showoff#6]
I like your showoff's idea very much. When I run commands as you instructed:

```
$: sudo gem install showoff
$: git clone git://github.com/schacon/showoff-wrangling-git.git
$: cd showoff-wrangling-git
$: showoff
```

However I get an js error in firebug:

```
$("#navmenu").menu is not a function
    flyOut: true\n                                   showoff.js (line 66)
```

And the page is idled at "loading presentation..."

Both **firefox** and **chrome** have this problem in my ubuntu 9.04, can you fix it?

**Comment by schacon** [comment]
i can't recreate this, so it's unlikely that i'll be able to fix it. if you provide a patch, i'll test and pull it in, though.

**Comment by corntrace** [comment]
OK, I found it. The js file "fg.menu.js" is only allowed the root to access it, as a non-root user I could not download it in the browser. You can change the permission of that file. Also I found that the "fg.menu.js" and "jTypeWriter.js" are executable, I think that's not necessary, isn't it :)

**Comment by schacon** [comment]
pushed a change to the exe bits, but the ownership stuff is not stored in git, that was done somehow when you checked it out.
