### ISSUE TITLE
Tilt -- The template engine of choice

### ISSUE THREAD

**Issue by bry4n** [schacon/showoff#7]
Allow people to choose the template engine by utilizing [Tilt](http://github.com/rtomayko/tilt). Ultimately, It might be cool if someone can use Mustache or Textile template for presentation. :-)

Hope you like the idea.

**Comment by defunkt** [comment]
I vote for keeping it Markdown only. It'll make it easier to offer extensions that provide Showoff-specific functionality and the documentation will be easier to write.

**Comment by bry4n** [comment]
True..

**Comment by schacon** [comment]
as i see that you've removed your fork, i'll close this
