### ISSUE TITLE
#NaN on 1.9.2

### ISSUE THREAD

**Issue by emachnic** [schacon/showoff#73]
When I try to go to http://localhost:9090 using MRI 1.9.2-p180, it tries to load and then redirects to http://localhost:9090/#NaN. I'm getting an HTTP status of 200 so I'm really not sure what's going on. Everything works fine in 1.8.7. Also, sometimes I get a segmentation fault though I can't seem to recreate it right now to give the stack trace.

**Comment by davetron5000** [comment]
any chance you can post your slides (or a version that causes this)?  I've been using it with 1.9.2 (I think?) without problems

**Comment by emachnic** [comment]
I was using the showoff-wrangling slides downloaded from here.

**Comment by davetron5000** [comment]
Seems to be an exception regarding image encoding; from the sinatra log:

```
Encoding::UndefinedConversionError - U+2018 from UTF-8 to ASCII-8BIT:
 /Users/davec/Archive/showoff/lib/showoff.rb:109:in `to_html'
 /Users/davec/Archive/showoff/lib/showoff.rb:109:in `block in process_markdown'
 /Users/davec/Archive/showoff/lib/showoff.rb:82:in `each'
 /Users/davec/Archive/showoff/lib/showoff.rb:82:in `process_markdown'
 /Users/davec/Archive/showoff/lib/showoff.rb:204:in `block in get_slides_html'
 /Users/davec/Archive/showoff/lib/showoff.rb:202:in `each'
 /Users/davec/Archive/showoff/lib/showoff.rb:202:in `get_slides_html'
 /Users/davec/Archive/showoff/lib/showoff.rb:289:in `slides'
 /Users/davec/Archive/showoff/lib/showoff.rb:378:in `block in <class:ShowOff>'
```

I did _not_ have `rdiscount` installed, so it was using Bluecloth, which I believe is the source of this bug. `gem install rdiscount` and things worked fine.

**Comment by emachnic** [comment]
Still having the issue. Here's a link to the very long stack trace. https://gist.github.com/857035

**Comment by davetron5000** [comment]
I cannot reproduce this.  I installed p180 via rvm, created a fresh gemset and installed all of showoff's dependencies.  In this state, I get the UTF encoding error above.  When I install rdiscount, everything works.

The stack trace in your gist is not the one I got (and posted above), so I'm guessing there is a problem with the version of Ruby you are running on your OS.  I don't have access to a Linux box (I'm on OS X Snow Leopard).

Do any other showoff presentations work for you?

Here's some of mine that work for me you could try (though they are _way_ less complex than the wrangling-git one we're discussing here):
- https://github.com/davetron5000/thanksgiving-rumble
- https://github.com/davetron5000/scala-boss
- https://github.com/davetron5000/sneaking-scala
- https://github.com/davetron5000/awesome-cli-ruby

**Comment by emachnic** [comment]
I tried the sneaking-scala one. Created a fresh gemset because I figured maybe I had some conflicts on the default one. Everything seems to be working fine now so I have no idea what the issue was.

**Comment by davetron5000** [comment]
I wonder if it's the same UTF issue surfacing as a different bug in your version of Ruby?  I wasn't able to grep the "wrangling" slides for unicode characters, but if you can find out which one it's using, and throw it into a working slide set, you might be able to figure out if that's it…
