### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by defunkt** [schacon/showoff#8]
Maybe this? 

http://www.htmldoc.org

**Comment by titanous** [comment]
One solution would be to write a Markdown -> Prawn converter.

[Kramdown](http://kramdown.rubyforge.org/) is a pure Ruby markdown parser, and it looks like it has a modular output system. I'm going to take a look at it this weekend.

**Comment by titanous** [comment]
It looks like my kramdown-pdf idea will work. I'll hack away at it, and it should be usable in a week or two. I've put together the framework, and I'll upload the repo as soon as it's half-working.

From there it's as simple as integrating it into showdown, and adding some nice 'slide' styles to the config.

**Comment by schacon** [comment]
that would be sweet - i wanted to do a prawn deal, but i hadn't looked into it yet.  thanks.

**Comment by titanous** [comment]
So I got started with kramdown-pdf, but found out very quickly that prawn-format, which allows for inline styles, is currently broken. Looking into fixing it now. This might take longer than expected.

**Comment by schacon** [comment]
in the interim, i've done a prince-pdf version, which takes the rendered html and makes a pdf.  it's actually not that bad, but it takes a while to run, and you have to have prince installed, which is not open source and not available in heroku.

**Comment by tmcw** [comment]
Has anyone had luck with images with the prince-pdf version?

**Comment by n1k0** [comment]
tmcw> Nope, no images in generated PDF here as well :/

**Comment by n1k0** [comment]
tmcw> fixed ([commit](http://github.com/n1k0/showoff/commit/f61cfdee0a25e5cb1515f1620b23e979b570d963))

**Comment by haad** [comment]
Maybe you can try to use this tool [1] as a replacement for prince-pdf it's opensource and it's based on webkit engine.

There is a PDFkit ruby gem which I have found which uses wkhtmltopdf as a backend.

[1]http://code.google.com/p/wkhtmltopdf/

**Comment by scottbale** [comment]
I have created a branch in which I swapped in PDFKit in place of Princely and it works wonderfully, at least for my preso and the example one. Here's my pull request https://github.com/schacon/showoff/pull/59

**Comment by schacon** [comment]
this is pretty well done now - the pdfkit thing rocks

**Comment by agocke** [comment]
Maybe I'm clueless, but how do you do PDF generation with this? Is there a PDF command line argument or something? Shouldn't there be if there isn't one?

**Comment by scottbale** [comment]
Just add "/pdf" to the end of your presentation URL, that should trigger the generation in your browser.

**Comment by agocke** [comment]
Thanks, that did generate a PDF. That may be worth placing in the README. However, the images did not show up. Is this expected behavior?

**Comment by scottbale** [comment]
You're right about the README. No, it's not expected behavior. There's been a lot of churn in PDF generation in last couple months, looks like there was a regression.

If you're not averse to changing source code, you can try changing line 130 of showoff.rb from
%(img src="./file/#{path}) :
to
%(img src="file://#{options.pres_dir}/#{path}) :
then rebuilding, reinstalling, restarting and trying again. Meanwhile, I'll try to make a fix and a pull request by this weekend. Don't you love OSS? :)

**Comment by agocke** [comment]
Sounds great, thanks.

Andy

**Comment by scottbale** [comment]
I created this pull request https://github.com/schacon/showoff/pull/74

**Comment by schacon** [comment]
awesome, thanks, I'll pull this in.
