### ISSUE TITLE
mention controls somewhere

### ISSUE THREAD

**Issue by xiongchiamiov** [schacon/showoff#9]
I was a bit baffled as to how to advance slides, until I took a look at the source of one of the generated files.  While you might think that -> and <- would be obvious, I can tell you that it isn't. :)

As a side note, it doesn't work with vimperator, but that's to be expected.

**Comment by schacon** [comment]
yeah, i want to make the example slides explain as much as possible, but i haven't finished them yet - I'll put that online soon.  i would also like to add this to the readme - i'll try to do this in the next few days, some of the common keybindings

**Comment by schacon** [comment]
this is in the readme now, thanks to crossblaim.  i will also eventually add hints to the example preso
